<?php
//=====================管理员后台
$mem['pay'][1][]=array(
	'',
	array(
		'module_config.php,1,payment,支付中心设置',
		'payment.php,1,payment',
		'member.php,1,payment,支付会员管理',
		'verify.php,1,payment,实名认证',
		'withdraw.php,1,payment,提现申请',
		'paymentmod.php,0,payment',
		/*'payment_user.php,1,payment,支付账户管理',
		'pickuplist.php,1,payment',
		'bank_account.php,1,payment',*/
		'cards.php,1,payment,充值卡管理',
		'cashflow.php,1,payment,资金明细',
		/*'member_charge.php,1,payment',*/
		'static.php,1,payment,系统资金总览',
	/*	'admin_commission.php,1,payment,佣金收入明细',*/
		'service_fee.php,1,payment,服务费配置',
	)
);
?>